# Generated by Django 6.0.1 on 2026-02-02 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='buy_price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='sell_price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
