# Generated by Django 6.0.1 on 2026-02-03 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_orderitem_buy_price_alter_orderitem_sell_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
