# Generated by Django 6.0.1 on 2026-02-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_round_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='round',
            name='travel_cost',
        ),
        migrations.AddField(
            model_name='round',
            name='travel_km',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
